### ISSUE TITLE
Could pretrained model consistent with official models?

### ISSUE THREAD

**Issue by HudsonHuang** [sweetcocoa/crepe-pytorch#2]
Thank you for your tidy implement.
How did you convert pretrained model to pytorch? I wonder it might be better to have a result comparison with official implement.

**Comment by sweetcocoa** [comment]
I just copied its weights and biases from the original implementation(Tensorflow). I did not test any quantitative comparison, But I found that this model outputs approximately(less than 1e-5~1e-6) the same values for the same input in the original implementation and in the middle layers and final output.
